service: dungeon-book-bot
frameworkVersion: "3"

custom:
  config: ${file(.env.yml):${opt:stage, self:provider.stage}}
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      noStart: true
provider:
  name: yandex-cloud
  runtime: nodejs14
  stage: dev
  region: ru-central1

plugins:
  - serverless-offline
  - "@yandex-cloud/serverless-plugin"
package:
  patterns:
    - '!**'
    - package.json
    - package-lock.json
    - api/*.js
    - logic/*.js
    - logic/*.json
functions:
  telegram-handler:
    handler: api/telegram.eventHandler
    memorySize: 128
    timeout: 5
    environment:
      bot_token: ${self:custom.config.bot_token}
    events:
      - http:
          path: webhook
          method: post
          cors: true